# Generated by Django 4.1 on 2022-09-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
